export const carecards = [
    {
        "cardID": "CC-1186891",
        "cardTitle": "Carecard 1",
        "observerFirstname": "Michael",
        "observerLastname": "Smith",
        "observerEmail": "user1@example.com",
        "observerDepartment": "Operations",
        "observerDesignation": "Intern",
        "observerCountry": "Canada",
        "observerLocation": "Remote Site",
        "observationType": "Equipment Failure",
        "peopleActs": 1,
        "condition": 1,
        "environmental": 1,
        "assetsEquipment": 1,
        "procedureSystem": 0,
        "quality": 1,
        "security": 1,
        "description": "Description for Carecard 1",
        "actionsTaken": "No",
        "suggestion": "Suggestion for Carecard 1",
        "status": "Uncompleted",
        "riskLevel": "High",
        "bypassSafety": 0,
        "lineOfFire": 0,
        "workingAtHeight": 1,
        "hotWork": 1,
        "driving": 0,
        "confinedSpace": 1,
        "permitToWork": 0,
        "energyIsolation": 1,
        "mechanicalLifting": 0,
        "correctiveAction": "Corrective action for Carecard 1",
        "editedBy": "Samuel Asare",
        "dateAdded": "2024-05-30 08:13:13",
        "profilepicture": ""
    },
    {
        "cardID": "CC-1186892",
        "cardTitle": "Carecard 2",
        "observerFirstname": "Sarah",
        "observerLastname": "Taylor",
        "observerEmail": "user2@example.com",
        "observerDepartment": "Operations",
        "observerDesignation": "Manager",
        "observerCountry": "Canada",
        "observerLocation": "Plant A",
        "observationType": "Unsafe Act",
        "peopleActs": 0,
        "condition": 0,
        "environmental": 0,
        "assetsEquipment": 0,
        "procedureSystem": 1,
        "quality": 1,
        "security": 0,
        "description": "Description for Carecard 2",
        "actionsTaken": "No",
        "suggestion": "Suggestion for Carecard 2",
        "status": "Uncompleted",
        "riskLevel": "High",
        "bypassSafety": 0,
        "lineOfFire": 0,
        "workingAtHeight": 0,
        "hotWork": 0,
        "driving": 0,
        "confinedSpace": 1,
        "permitToWork": 1,
        "energyIsolation": 0,
        "mechanicalLifting": 0,
        "correctiveAction": "Corrective action for Carecard 2",
        "editedBy": "Kofi Arthur",
        "dateAdded": "2024-06-29 05:41:28",
        "profilepicture": "profile2.jpg"
    },
    {
        "cardID": "CC-1186893",
        "cardTitle": "Carecard 3",
        "observerFirstname": "Mary",
        "observerLastname": "Brown",
        "observerEmail": "user3@example.com",
        "observerDepartment": "Production",
        "observerDesignation": "Intern",
        "observerCountry": "UK",
        "observerLocation": "HQ",
        "observationType": "Equipment Failure",
        "peopleActs": 1,
        "condition": 0,
        "environmental": 0,
        "assetsEquipment": 1,
        "procedureSystem": 0,
        "quality": 0,
        "security": 0,
        "description": "Description for Carecard 3",
        "actionsTaken": "No",
        "suggestion": "Suggestion for Carecard 3",
        "status": "Pending",
        "riskLevel": "Low",
        "bypassSafety": 0,
        "lineOfFire": 0,
        "workingAtHeight": 0,
        "hotWork": 0,
        "driving": 0,
        "confinedSpace": 0,
        "permitToWork": 1,
        "energyIsolation": 1,
        "mechanicalLifting": 1,
        "correctiveAction": "Corrective action for Carecard 3",
        "editedBy": "Samuel Asare",
        "dateAdded": "2024-05-31 09:31:39",
        "profilepicture": "profile3.jpg"
    },
    {
        "cardID": "CC-1186894",
        "cardTitle": "Carecard 4",
        "observerFirstname": "John",
        "observerLastname": "Taylor",
        "observerEmail": "user4@example.com",
        "observerDepartment": "Operations",
        "observerDesignation": "Supervisor",
        "observerCountry": "Canada",
        "observerLocation": "Plant B",
        "observationType": "Procedure Violation",
        "peopleActs": 1,
        "condition": 0,
        "environmental": 0,
        "assetsEquipment": 0,
        "procedureSystem": 1,
        "quality": 1,
        "security": 0,
        "description": "Description for Carecard 4",
        "actionsTaken": "No",
        "suggestion": "Suggestion for Carecard 4",
        "status": "Uncompleted",
        "riskLevel": "High",
        "bypassSafety": 1,
        "lineOfFire": 1,
        "workingAtHeight": 1,
        "hotWork": 0,
        "driving": 1,
        "confinedSpace": 1,
        "permitToWork": 1,
        "energyIsolation": 1,
        "mechanicalLifting": 1,
        "correctiveAction": "Corrective action for Carecard 4",
        "editedBy": "Kofi Arthur",
        "dateAdded": "2023-03-05 09:20:47",
        "profilepicture": ""
    },
    {
        "cardID": "CC-1186895",
        "cardTitle": "Carecard 5",
        "observerFirstname": "Mary",
        "observerLastname": "Brown",
        "observerEmail": "user5@example.com",
        "observerDepartment": "Logistics",
        "observerDesignation": "Intern",
        "observerCountry": "Canada",
        "observerLocation": "Remote Site",
        "observationType": "Procedure Violation",
        "peopleActs": 0,
        "condition": 0,
        "environmental": 0,
        "assetsEquipment": 1,
        "procedureSystem": 1,
        "quality": 0,
        "security": 1,
        "description": "Description for Carecard 5",
        "actionsTaken": "Yes",
        "suggestion": "Suggestion for Carecard 5",
        "status": "Completed",
        "riskLevel": "Low",
        "bypassSafety": 0,
        "lineOfFire": 0,
        "workingAtHeight": 0,
        "hotWork": 1,
        "driving": 0,
        "confinedSpace": 1,
        "permitToWork": 1,
        "energyIsolation": 1,
        "mechanicalLifting": 1,
        "correctiveAction": "Corrective action for Carecard 5",
        "editedBy": "Samuel Asare",
        "dateAdded": "2023-11-28 20:53:52",
        "profilepicture": "profile5.jpg"
    },
    {
        "cardID": "CC-1186896",
        "cardTitle": "Carecard 6",
        "observerFirstname": "Samuel",
        "observerLastname": "Taylor",
        "observerEmail": "user6@example.com",
        "observerDepartment": "Maintenance",
        "observerDesignation": "Supervisor",
        "observerCountry": "UK",
        "observerLocation": "Plant B",
        "observationType": "Procedure Violation",
        "peopleActs": 0,
        "condition": 1,
        "environmental": 0,
        "assetsEquipment": 1,
        "procedureSystem": 0,
        "quality": 0,
        "security": 0,
        "description": "Description for Carecard 6",
        "actionsTaken": "No",
        "suggestion": "Suggestion for Carecard 6",
        "status": "Pending",
        "riskLevel": "Medium",
        "bypassSafety": 0,
        "lineOfFire": 1,
        "workingAtHeight": 1,
        "hotWork": 1,
        "driving": 0,
        "confinedSpace": 1,
        "permitToWork": 1,
        "energyIsolation": 0,
        "mechanicalLifting": 1,
        "correctiveAction": "Corrective action for Carecard 6",
        "editedBy": "Jane Smith",
        "dateAdded": "2023-04-06 08:33:33",
        "profilepicture": "profile6.jpg"
    },
    {
        "cardID": "CC-1186897",
        "cardTitle": "Carecard 7",
        "observerFirstname": "Victoria",
        "observerLastname": "Doe",
        "observerEmail": "user7@example.com",
        "observerDepartment": "Operations",
        "observerDesignation": "National Service Personnel",
        "observerCountry": "India",
        "observerLocation": "Remote Site",
        "observationType": "Procedure Violation",
        "peopleActs": 1,
        "condition": 1,
        "environmental": 0,
        "assetsEquipment": 0,
        "procedureSystem": 0,
        "quality": 1,
        "security": 0,
        "description": "Description for Carecard 7",
        "actionsTaken": "Yes",
        "suggestion": "Suggestion for Carecard 7",
        "status": "Completed",
        "riskLevel": "High",
        "bypassSafety": 0,
        "lineOfFire": 0,
        "workingAtHeight": 1,
        "hotWork": 0,
        "driving": 0,
        "confinedSpace": 0,
        "permitToWork": 1,
        "energyIsolation": 0,
        "mechanicalLifting": 1,
        "correctiveAction": "Corrective action for Carecard 7",
        "editedBy": "Samuel Asare",
        "dateAdded": "2024-06-25 05:32:21",
        "profilepicture": ""
    },
    {
        "cardID": "CC-1186898",
        "cardTitle": "Carecard 8",
        "observerFirstname": "Victoria",
        "observerLastname": "Taylor",
        "observerEmail": "user8@example.com",
        "observerDepartment": "Logistics",
        "observerDesignation": "Manager",
        "observerCountry": "India",
        "observerLocation": "Plant A",
        "observationType": "Equipment Failure",
        "peopleActs": 1,
        "condition": 1,
        "environmental": 0,
        "assetsEquipment": 1,
        "procedureSystem": 1,
        "quality": 1,
        "security": 0,
        "description": "Description for Carecard 8",
        "actionsTaken": "No",
        "suggestion": "Suggestion for Carecard 8",
        "status": "Pending",
        "riskLevel": "High",
        "bypassSafety": 1,
        "lineOfFire": 1,
        "workingAtHeight": 1,
        "hotWork": 1,
        "driving": 1,
        "confinedSpace": 1,
        "permitToWork": 1,
        "energyIsolation": 0,
        "mechanicalLifting": 0,
        "correctiveAction": "Corrective action for Carecard 8",
        "editedBy": "Jane Smith",
        "dateAdded": "2024-05-14 15:27:02",
        "profilepicture": ""
    },
    {
        "cardID": "CC-1186899",
        "cardTitle": "Carecard 9",
        "observerFirstname": "Michael",
        "observerLastname": "Koomson",
        "observerEmail": "user9@example.com",
        "observerDepartment": "HSE",
        "observerDesignation": "National Service Personnel",
        "observerCountry": "Canada",
        "observerLocation": "HQ",
        "observationType": "Equipment Failure",
        "peopleActs": 1,
        "condition": 1,
        "environmental": 1,
        "assetsEquipment": 0,
        "procedureSystem": 1,
        "quality": 0,
        "security": 0,
        "description": "Description for Carecard 9",
        "actionsTaken": "Yes",
        "suggestion": "Suggestion for Carecard 9",
        "status": "Pending",
        "riskLevel": "High",
        "bypassSafety": 1,
        "lineOfFire": 0,
        "workingAtHeight": 1,
        "hotWork": 0,
        "driving": 1,
        "confinedSpace": 0,
        "permitToWork": 0,
        "energyIsolation": 1,
        "mechanicalLifting": 0,
        "correctiveAction": "Corrective action for Carecard 9",
        "editedBy": "Jane Smith",
        "dateAdded": "2023-09-18 17:37:31",
        "profilepicture": "profile9.jpg"
    },
    {
        "cardID": "CC-1186900",
        "cardTitle": "Carecard 10",
        "observerFirstname": "Mary",
        "observerLastname": "Johnson",
        "observerEmail": "user10@example.com",
        "observerDepartment": "Maintenance",
        "observerDesignation": "National Service Personnel",
        "observerCountry": "UK",
        "observerLocation": "Plant A",
        "observationType": "Equipment Failure",
        "peopleActs": 1,
        "condition": 0,
        "environmental": 1,
        "assetsEquipment": 0,
        "procedureSystem": 0,
        "quality": 1,
        "security": 0,
        "description": "Description for Carecard 10",
        "actionsTaken": "Yes",
        "suggestion": "Suggestion for Carecard 10",
        "status": "Uncompleted",
        "riskLevel": "Medium",
        "bypassSafety": 0,
        "lineOfFire": 1,
        "workingAtHeight": 1,
        "hotWork": 0,
        "driving": 0,
        "confinedSpace": 0,
        "permitToWork": 1,
        "energyIsolation": 1,
        "mechanicalLifting": 0,
        "correctiveAction": "Corrective action for Carecard 10",
        "editedBy": "Jane Smith",
        "dateAdded": "2024-09-16 08:20:51",
        "profilepicture": "profile10.jpg"
    },
    {
        "cardID": "CC-1186901",
        "cardTitle": "Carecard 11",
        "observerFirstname": "Victoria",
        "observerLastname": "Asare",
        "observerEmail": "user11@example.com",
        "observerDepartment": "Production",
        "observerDesignation": "National Service Personnel",
        "observerCountry": "India",
        "observerLocation": "HQ",
        "observationType": "Equipment Failure",
        "peopleActs": 0,
        "condition": 1,
        "environmental": 0,
        "assetsEquipment": 0,
        "procedureSystem": 1,
        "quality": 1,
        "security": 1,
        "description": "Description for Carecard 11",
        "actionsTaken": "No",
        "suggestion": "Suggestion for Carecard 11",
        "status": "Completed",
        "riskLevel": "Medium",
        "bypassSafety": 0,
        "lineOfFire": 0,
        "workingAtHeight": 0,
        "hotWork": 1,
        "driving": 0,
        "confinedSpace": 0,
        "permitToWork": 0,
        "energyIsolation": 0,
        "mechanicalLifting": 0,
        "correctiveAction": "Corrective action for Carecard 11",
        "editedBy": "Jane Smith",
        "dateAdded": "2024-04-15 17:45:23",
        "profilepicture": ""
    },
    {
        "cardID": "CC-1186902",
        "cardTitle": "Carecard 12",
        "observerFirstname": "John",
        "observerLastname": "Asare",
        "observerEmail": "user12@example.com",
        "observerDepartment": "HSE",
        "observerDesignation": "National Service Personnel",
        "observerCountry": "India",
        "observerLocation": "Plant A",
        "observationType": "Procedure Violation",
        "peopleActs": 1,
        "condition": 1,
        "environmental": 0,
        "assetsEquipment": 1,
        "procedureSystem": 0,
        "quality": 1,
        "security": 0,
        "description": "Description for Carecard 12",
        "actionsTaken": "No",
        "suggestion": "Suggestion for Carecard 12",
        "status": "Completed",
        "riskLevel": "High",
        "bypassSafety": 0,
        "lineOfFire": 0,
        "workingAtHeight": 0,
        "hotWork": 0,
        "driving": 0,
        "confinedSpace": 0,
        "permitToWork": 0,
        "energyIsolation": 1,
        "mechanicalLifting": 1,
        "correctiveAction": "Corrective action for Carecard 12",
        "editedBy": "Samuel Wilson",
        "dateAdded": "2023-10-25 14:00:50",
        "profilepicture": ""
    },
    {
        "cardID": "CC-1186903",
        "cardTitle": "Carecard 13",
        "observerFirstname": "Michael",
        "observerLastname": "Koomson",
        "observerEmail": "user13@example.com",
        "observerDepartment": "Operations",
        "observerDesignation": "Supervisor",
        "observerCountry": "USA",
        "observerLocation": "HQ",
        "observationType": "Equipment Failure",
        "peopleActs": 0,
        "condition": 0,
        "environmental": 0,
        "assetsEquipment": 0,
        "procedureSystem": 1,
        "quality": 0,
        "security": 0,
        "description": "Description for Carecard 13",
        "actionsTaken": "No",
        "suggestion": "Suggestion for Carecard 13",
        "status": "Completed",
        "riskLevel": "Medium",
        "bypassSafety": 0,
        "lineOfFire": 0,
        "workingAtHeight": 0,
        "hotWork": 1,
        "driving": 0,
        "confinedSpace": 0,
        "permitToWork": 1,
        "energyIsolation": 0,
        "mechanicalLifting": 1,
        "correctiveAction": "Corrective action for Carecard 13",
        "editedBy": "Samuel Wilson",
        "dateAdded": "2023-12-29 04:37:59",
        "profilepicture": ""
    },
    {
        "cardID": "CC-1186904",
        "cardTitle": "Carecard 14",
        "observerFirstname": "Michael",
        "observerLastname": "Taylor",
        "observerEmail": "user14@example.com",
        "observerDepartment": "Production",
        "observerDesignation": "National Service Personnel",
        "observerCountry": "Canada",
        "observerLocation": "HQ",
        "observationType": "Unsafe Act",
        "peopleActs": 0,
        "condition": 1,
        "environmental": 0,
        "assetsEquipment": 1,
        "procedureSystem": 1,
        "quality": 0,
        "security": 0,
        "description": "Description for Carecard 14",
        "actionsTaken": "No",
        "suggestion": "Suggestion for Carecard 14",
        "status": "Completed",
        "riskLevel": "High",
        "bypassSafety": 1,
        "lineOfFire": 1,
        "workingAtHeight": 0,
        "hotWork": 0,
        "driving": 1,
        "confinedSpace": 1,
        "permitToWork": 0,
        "energyIsolation": 1,
        "mechanicalLifting": 0,
        "correctiveAction": "Corrective action for Carecard 14",
        "editedBy": "Kofi Arthur",
        "dateAdded": "2024-11-23 22:10:09",
        "profilepicture": ""
    },
    {
        "cardID": "CC-1186905",
        "cardTitle": "Carecard 15",
        "observerFirstname": "Sarah",
        "observerLastname": "Koomson",
        "observerEmail": "user15@example.com",
        "observerDepartment": "HSE",
        "observerDesignation": "National Service Personnel",
        "observerCountry": "UK",
        "observerLocation": "HQ",
        "observationType": "Unsafe Act",
        "peopleActs": 0,
        "condition": 1,
        "environmental": 1,
        "assetsEquipment": 0,
        "procedureSystem": 0,
        "quality": 0,
        "security": 1,
        "description": "Description for Carecard 15",
        "actionsTaken": "No",
        "suggestion": "Suggestion for Carecard 15",
        "status": "Uncompleted",
        "riskLevel": "High",
        "bypassSafety": 1,
        "lineOfFire": 0,
        "workingAtHeight": 1,
        "hotWork": 1,
        "driving": 0,
        "confinedSpace": 0,
        "permitToWork": 1,
        "energyIsolation": 1,
        "mechanicalLifting": 1,
        "correctiveAction": "Corrective action for Carecard 15",
        "editedBy": "Jane Smith",
        "dateAdded": "2023-01-22 19:23:56",
        "profilepicture": "profile15.jpg"
    },
    {
        "cardID": "CC-1186906",
        "cardTitle": "Carecard 16",
        "observerFirstname": "Victoria",
        "observerLastname": "Koomson",
        "observerEmail": "user16@example.com",
        "observerDepartment": "Maintenance",
        "observerDesignation": "National Service Personnel",
        "observerCountry": "Canada",
        "observerLocation": "Remote Site",
        "observationType": "Unsafe Act",
        "peopleActs": 0,
        "condition": 0,
        "environmental": 1,
        "assetsEquipment": 0,
        "procedureSystem": 1,
        "quality": 1,
        "security": 1,
        "description": "Description for Carecard 16",
        "actionsTaken": "Yes",
        "suggestion": "Suggestion for Carecard 16",
        "status": "Uncompleted",
        "riskLevel": "High",
        "bypassSafety": 1,
        "lineOfFire": 1,
        "workingAtHeight": 0,
        "hotWork": 1,
        "driving": 0,
        "confinedSpace": 0,
        "permitToWork": 0,
        "energyIsolation": 1,
        "mechanicalLifting": 1,
        "correctiveAction": "Corrective action for Carecard 16",
        "editedBy": "Samuel Wilson",
        "dateAdded": "2023-04-18 03:09:29",
        "profilepicture": ""
    },
    {
        "cardID": "CC-1186907",
        "cardTitle": "Carecard 17",
        "observerFirstname": "Alice",
        "observerLastname": "Asare",
        "observerEmail": "user17@example.com",
        "observerDepartment": "Logistics",
        "observerDesignation": "National Service Personnel",
        "observerCountry": "USA",
        "observerLocation": "HQ",
        "observationType": "Equipment Failure",
        "peopleActs": 0,
        "condition": 0,
        "environmental": 0,
        "assetsEquipment": 0,
        "procedureSystem": 1,
        "quality": 1,
        "security": 0,
        "description": "Description for Carecard 17",
        "actionsTaken": "Yes",
        "suggestion": "Suggestion for Carecard 17",
        "status": "Uncompleted",
        "riskLevel": "Low",
        "bypassSafety": 0,
        "lineOfFire": 1,
        "workingAtHeight": 1,
        "hotWork": 0,
        "driving": 1,
        "confinedSpace": 0,
        "permitToWork": 0,
        "energyIsolation": 1,
        "mechanicalLifting": 1,
        "correctiveAction": "Corrective action for Carecard 17",
        "editedBy": "Jane Smith",
        "dateAdded": "2024-09-08 02:52:04",
        "profilepicture": "profile17.jpg"
    },
    {
        "cardID": "CC-1186908",
        "cardTitle": "Carecard 18",
        "observerFirstname": "Alice",
        "observerLastname": "Doe",
        "observerEmail": "user18@example.com",
        "observerDepartment": "Production",
        "observerDesignation": "National Service Personnel",
        "observerCountry": "UK",
        "observerLocation": "Plant A",
        "observationType": "Equipment Failure",
        "peopleActs": 1,
        "condition": 0,
        "environmental": 1,
        "assetsEquipment": 1,
        "procedureSystem": 0,
        "quality": 1,
        "security": 0,
        "description": "Description for Carecard 18",
        "actionsTaken": "Yes",
        "suggestion": "Suggestion for Carecard 18",
        "status": "Completed",
        "riskLevel": "Medium",
        "bypassSafety": 0,
        "lineOfFire": 0,
        "workingAtHeight": 0,
        "hotWork": 1,
        "driving": 0,
        "confinedSpace": 0,
        "permitToWork": 1,
        "energyIsolation": 1,
        "mechanicalLifting": 1,
        "correctiveAction": "Corrective action for Carecard 18",
        "editedBy": "Jane Smith",
        "dateAdded": "2024-03-11 20:18:44",
        "profilepicture": ""
    },
    {
        "cardID": "CC-1186909",
        "cardTitle": "Carecard 19",
        "observerFirstname": "Sarah",
        "observerLastname": "Doe",
        "observerEmail": "user19@example.com",
        "observerDepartment": "Maintenance",
        "observerDesignation": "Manager",
        "observerCountry": "India",
        "observerLocation": "Remote Site",
        "observationType": "Substandard Hazard",
        "peopleActs": 1,
        "condition": 1,
        "environmental": 1,
        "assetsEquipment": 0,
        "procedureSystem": 0,
        "quality": 1,
        "security": 1,
        "description": "Description for Carecard 19",
        "actionsTaken": "Yes",
        "suggestion": "Suggestion for Carecard 19",
        "status": "Uncompleted",
        "riskLevel": "High",
        "bypassSafety": 0,
        "lineOfFire": 0,
        "workingAtHeight": 1,
        "hotWork": 0,
        "driving": 1,
        "confinedSpace": 1,
        "permitToWork": 1,
        "energyIsolation": 1,
        "mechanicalLifting": 0,
        "correctiveAction": "Corrective action for Carecard 19",
        "editedBy": "Kofi Arthur",
        "dateAdded": "2024-05-05 08:26:20",
        "profilepicture": ""
    },
    {
        "cardID": "CC-1186910",
        "cardTitle": "Carecard 20",
        "observerFirstname": "Mary",
        "observerLastname": "Koomson",
        "observerEmail": "user20@example.com",
        "observerDepartment": "Maintenance",
        "observerDesignation": "National Service Personnel",
        "observerCountry": "UK",
        "observerLocation": "Plant A",
        "observationType": "Equipment Failure",
        "peopleActs": 0,
        "condition": 0,
        "environmental": 0,
        "assetsEquipment": 1,
        "procedureSystem": 1,
        "quality": 1,
        "security": 0,
        "description": "Description for Carecard 20",
        "actionsTaken": "Yes",
        "suggestion": "Suggestion for Carecard 20",
        "status": "Completed",
        "riskLevel": "Medium",
        "bypassSafety": 0,
        "lineOfFire": 0,
        "workingAtHeight": 0,
        "hotWork": 1,
        "driving": 0,
        "confinedSpace": 1,
        "permitToWork": 0,
        "energyIsolation": 0,
        "mechanicalLifting": 0,
        "correctiveAction": "Corrective action for Carecard 20",
        "editedBy": "Kofi Arthur",
        "dateAdded": "2023-01-30 18:25:19",
        "profilepicture": "profile20.jpg"
    },
    {
        "cardID": "CC-1186911",
        "cardTitle": "Carecard 21",
        "observerFirstname": "Alice",
        "observerLastname": "Brown",
        "observerEmail": "user21@example.com",
        "observerDepartment": "HSE",
        "observerDesignation": "Technician",
        "observerCountry": "Canada",
        "observerLocation": "Remote Site",
        "observationType": "Procedure Violation",
        "peopleActs": 0,
        "condition": 1,
        "environmental": 1,
        "assetsEquipment": 1,
        "procedureSystem": 0,
        "quality": 1,
        "security": 1,
        "description": "Description for Carecard 21",
        "actionsTaken": "No",
        "suggestion": "Suggestion for Carecard 21",
        "status": "Uncompleted",
        "riskLevel": "Medium",
        "bypassSafety": 0,
        "lineOfFire": 0,
        "workingAtHeight": 0,
        "hotWork": 1,
        "driving": 1,
        "confinedSpace": 1,
        "permitToWork": 0,
        "energyIsolation": 1,
        "mechanicalLifting": 1,
        "correctiveAction": "Corrective action for Carecard 21",
        "editedBy": "Samuel Wilson",
        "dateAdded": "2023-04-16 08:46:59",
        "profilepicture": ""
    },
    {
        "cardID": "CC-1186912",
        "cardTitle": "Carecard 22",
        "observerFirstname": "Sarah",
        "observerLastname": "Johnson",
        "observerEmail": "user22@example.com",
        "observerDepartment": "Production",
        "observerDesignation": "Intern",
        "observerCountry": "India",
        "observerLocation": "Plant A",
        "observationType": "Procedure Violation",
        "peopleActs": 1,
        "condition": 1,
        "environmental": 1,
        "assetsEquipment": 0,
        "procedureSystem": 0,
        "quality": 1,
        "security": 0,
        "description": "Description for Carecard 22",
        "actionsTaken": "Yes",
        "suggestion": "Suggestion for Carecard 22",
        "status": "Pending",
        "riskLevel": "Medium",
        "bypassSafety": 0,
        "lineOfFire": 1,
        "workingAtHeight": 1,
        "hotWork": 1,
        "driving": 0,
        "confinedSpace": 0,
        "permitToWork": 1,
        "energyIsolation": 1,
        "mechanicalLifting": 0,
        "correctiveAction": "Corrective action for Carecard 22",
        "editedBy": "Jane Smith",
        "dateAdded": "2023-06-04 10:54:24",
        "profilepicture": ""
    },
    {
        "cardID": "CC-1186913",
        "cardTitle": "Carecard 23",
        "observerFirstname": "Mary",
        "observerLastname": "Asare",
        "observerEmail": "user23@example.com",
        "observerDepartment": "Logistics",
        "observerDesignation": "Manager",
        "observerCountry": "Canada",
        "observerLocation": "Plant B",
        "observationType": "Procedure Violation",
        "peopleActs": 1,
        "condition": 0,
        "environmental": 0,
        "assetsEquipment": 0,
        "procedureSystem": 0,
        "quality": 1,
        "security": 1,
        "description": "Description for Carecard 23",
        "actionsTaken": "No",
        "suggestion": "Suggestion for Carecard 23",
        "status": "Uncompleted",
        "riskLevel": "High",
        "bypassSafety": 0,
        "lineOfFire": 0,
        "workingAtHeight": 0,
        "hotWork": 0,
        "driving": 1,
        "confinedSpace": 1,
        "permitToWork": 0,
        "energyIsolation": 0,
        "mechanicalLifting": 0,
        "correctiveAction": "Corrective action for Carecard 23",
        "editedBy": "Kofi Arthur",
        "dateAdded": "2023-09-11 05:27:16",
        "profilepicture": ""
    },
    {
        "cardID": "CC-1186914",
        "cardTitle": "Carecard 24",
        "observerFirstname": "John",
        "observerLastname": "Smith",
        "observerEmail": "user24@example.com",
        "observerDepartment": "HSE",
        "observerDesignation": "Technician",
        "observerCountry": "USA",
        "observerLocation": "Plant A",
        "observationType": "Procedure Violation",
        "peopleActs": 0,
        "condition": 0,
        "environmental": 0,
        "assetsEquipment": 0,
        "procedureSystem": 1,
        "quality": 0,
        "security": 1,
        "description": "Description for Carecard 24",
        "actionsTaken": "No",
        "suggestion": "Suggestion for Carecard 24",
        "status": "Pending",
        "riskLevel": "High",
        "bypassSafety": 0,
        "lineOfFire": 0,
        "workingAtHeight": 0,
        "hotWork": 0,
        "driving": 0,
        "confinedSpace": 1,
        "permitToWork": 0,
        "energyIsolation": 1,
        "mechanicalLifting": 1,
        "correctiveAction": "Corrective action for Carecard 24",
        "editedBy": "Jane Smith",
        "dateAdded": "2024-02-11 10:20:01",
        "profilepicture": "profile24.jpg"
    },
    {
        "cardID": "CC-1186915",
        "cardTitle": "Carecard 25",
        "observerFirstname": "Alice",
        "observerLastname": "Doe",
        "observerEmail": "user25@example.com",
        "observerDepartment": "Operations",
        "observerDesignation": "Intern",
        "observerCountry": "UK",
        "observerLocation": "Plant A",
        "observationType": "Substandard Hazard",
        "peopleActs": 1,
        "condition": 0,
        "environmental": 0,
        "assetsEquipment": 1,
        "procedureSystem": 1,
        "quality": 0,
        "security": 1,
        "description": "Description for Carecard 25",
        "actionsTaken": "Yes",
        "suggestion": "Suggestion for Carecard 25",
        "status": "Uncompleted",
        "riskLevel": "Medium",
        "bypassSafety": 0,
        "lineOfFire": 0,
        "workingAtHeight": 0,
        "hotWork": 1,
        "driving": 0,
        "confinedSpace": 1,
        "permitToWork": 0,
        "energyIsolation": 0,
        "mechanicalLifting": 0,
        "correctiveAction": "Corrective action for Carecard 25",
        "editedBy": "Kofi Arthur",
        "dateAdded": "2023-01-28 20:28:35",
        "profilepicture": ""
    },
    {
        "cardID": "CC-1186916",
        "cardTitle": "Carecard 26",
        "observerFirstname": "Victoria",
        "observerLastname": "Wilson",
        "observerEmail": "user26@example.com",
        "observerDepartment": "Logistics",
        "observerDesignation": "National Service Personnel",
        "observerCountry": "USA",
        "observerLocation": "Plant B",
        "observationType": "Procedure Violation",
        "peopleActs": 0,
        "condition": 1,
        "environmental": 1,
        "assetsEquipment": 0,
        "procedureSystem": 1,
        "quality": 1,
        "security": 0,
        "description": "Description for Carecard 26",
        "actionsTaken": "Yes",
        "suggestion": "Suggestion for Carecard 26",
        "status": "Pending",
        "riskLevel": "Low",
        "bypassSafety": 1,
        "lineOfFire": 1,
        "workingAtHeight": 0,
        "hotWork": 0,
        "driving": 1,
        "confinedSpace": 0,
        "permitToWork": 1,
        "energyIsolation": 1,
        "mechanicalLifting": 1,
        "correctiveAction": "Corrective action for Carecard 26",
        "editedBy": "Samuel Asare",
        "dateAdded": "2023-01-22 20:37:01",
        "profilepicture": ""
    },
    {
        "cardID": "CC-1186917",
        "cardTitle": "Carecard 27",
        "observerFirstname": "Alice",
        "observerLastname": "Asare",
        "observerEmail": "user27@example.com",
        "observerDepartment": "Operations",
        "observerDesignation": "Intern",
        "observerCountry": "USA",
        "observerLocation": "Plant B",
        "observationType": "Substandard Hazard",
        "peopleActs": 0,
        "condition": 1,
        "environmental": 1,
        "assetsEquipment": 1,
        "procedureSystem": 1,
        "quality": 0,
        "security": 0,
        "description": "Description for Carecard 27",
        "actionsTaken": "No",
        "suggestion": "Suggestion for Carecard 27",
        "status": "Uncompleted",
        "riskLevel": "High",
        "bypassSafety": 0,
        "lineOfFire": 0,
        "workingAtHeight": 1,
        "hotWork": 0,
        "driving": 0,
        "confinedSpace": 0,
        "permitToWork": 1,
        "energyIsolation": 1,
        "mechanicalLifting": 0,
        "correctiveAction": "Corrective action for Carecard 27",
        "editedBy": "Samuel Asare",
        "dateAdded": "2024-04-06 19:13:04",
        "profilepicture": ""
    },
    {
        "cardID": "CC-1186918",
        "cardTitle": "Carecard 28",
        "observerFirstname": "Victoria",
        "observerLastname": "Brown",
        "observerEmail": "user28@example.com",
        "observerDepartment": "Production",
        "observerDesignation": "Manager",
        "observerCountry": "UK",
        "observerLocation": "Plant B",
        "observationType": "Equipment Failure",
        "peopleActs": 0,
        "condition": 1,
        "environmental": 1,
        "assetsEquipment": 0,
        "procedureSystem": 0,
        "quality": 0,
        "security": 0,
        "description": "Description for Carecard 28",
        "actionsTaken": "No",
        "suggestion": "Suggestion for Carecard 28",
        "status": "Uncompleted",
        "riskLevel": "High",
        "bypassSafety": 1,
        "lineOfFire": 1,
        "workingAtHeight": 1,
        "hotWork": 0,
        "driving": 1,
        "confinedSpace": 1,
        "permitToWork": 0,
        "energyIsolation": 1,
        "mechanicalLifting": 1,
        "correctiveAction": "Corrective action for Carecard 28",
        "editedBy": "Samuel Asare",
        "dateAdded": "2024-04-14 18:58:55",
        "profilepicture": "profile28.jpg"
    },
    {
        "cardID": "CC-1186919",
        "cardTitle": "Carecard 29",
        "observerFirstname": "Samuel",
        "observerLastname": "Johnson",
        "observerEmail": "user29@example.com",
        "observerDepartment": "Logistics",
        "observerDesignation": "National Service Personnel",
        "observerCountry": "Ghana",
        "observerLocation": "Remote Site",
        "observationType": "Unsafe Act",
        "peopleActs": 1,
        "condition": 1,
        "environmental": 1,
        "assetsEquipment": 1,
        "procedureSystem": 0,
        "quality": 0,
        "security": 1,
        "description": "Description for Carecard 29",
        "actionsTaken": "No",
        "suggestion": "Suggestion for Carecard 29",
        "status": "Pending",
        "riskLevel": "High",
        "bypassSafety": 1,
        "lineOfFire": 1,
        "workingAtHeight": 0,
        "hotWork": 1,
        "driving": 0,
        "confinedSpace": 1,
        "permitToWork": 0,
        "energyIsolation": 1,
        "mechanicalLifting": 0,
        "correctiveAction": "Corrective action for Carecard 29",
        "editedBy": "Kofi Arthur",
        "dateAdded": "2024-11-04 21:18:14",
        "profilepicture": "profile29.jpg"
    },
    {
        "cardID": "CC-1186920",
        "cardTitle": "Carecard 30",
        "observerFirstname": "Michael",
        "observerLastname": "Johnson",
        "observerEmail": "user30@example.com",
        "observerDepartment": "Production",
        "observerDesignation": "Technician",
        "observerCountry": "USA",
        "observerLocation": "HQ",
        "observationType": "Unsafe Act",
        "peopleActs": 1,
        "condition": 1,
        "environmental": 1,
        "assetsEquipment": 1,
        "procedureSystem": 0,
        "quality": 0,
        "security": 0,
        "description": "Description for Carecard 30",
        "actionsTaken": "Yes",
        "suggestion": "Suggestion for Carecard 30",
        "status": "Uncompleted",
        "riskLevel": "Low",
        "bypassSafety": 0,
        "lineOfFire": 0,
        "workingAtHeight": 0,
        "hotWork": 1,
        "driving": 0,
        "confinedSpace": 1,
        "permitToWork": 1,
        "energyIsolation": 0,
        "mechanicalLifting": 0,
        "correctiveAction": "Corrective action for Carecard 30",
        "editedBy": "Samuel Asare",
        "dateAdded": "2024-09-17 20:21:43",
        "profilepicture": ""
    }
]

export const recentcards ={
    "cards": [
        {
            "cardID": "CC-7691714",
            "cardTitle": "Rodents in the Kitchen 🐀",
            "observerFirstname": "Barry",
            "observerLastname": "Allen",
            "observerEmail": "user1@example.com",
            "observerDepartment": "IT",
            "observerDesignation": "Other",
            "observerCountry": "Ghana",
            "observerLocation": "Head Office",
            "observationType": "Substandard Hazard",
            "peopleActs": 0,
            "condition": 1,
            "environmental": 1,
            "assetsEquipment": 0,
            "procedureSystem": 0,
            "quality": 0,
            "security": 0,
            "description": "I have observed that there are rodents (rats to be specific) in the room designated for our meals, the canteen. This could lead to several health risks, structual damages and to some forseeable degree, damage the company's reputation.",
            "actionsTaken": "No",
            "suggestion": "I would like to suggest that an initiative to exterminate them or one that will make the environment less condusive for them to breed, should be taken.",
            "status": "Pending",
            "riskLevel": null,
            "bypassSafety": 0,
            "lineOfFire": 0,
            "workingAtHeight": 0,
            "hotWorK": 0,
            "driving": 0,
            "confinedSpace": 0,
            "permitToWork": 0,
            "energyIsolation": 0,
            "mechanicalLifting": 0,
            "correctiveAction": null,
            "editedBy": null,
            "dateAdded": "2024-12-04T15:40:22.000Z"
        },
        {
            "cardID": "CC-8360458",
            "cardTitle": "",
            "observerFirstname": "Dean ",
            "observerLastname": "Glenn",
            "observerEmail": "user4@example.com",
            "observerDepartment": "Operations",
            "observerDesignation": "Other",
            "observerCountry": "Ghana",
            "observerLocation": "Head Office",
            "observationType": "Positive",
            "peopleActs": 1,
            "condition": 0,
            "environmental": 0,
            "assetsEquipment": 0,
            "procedureSystem": 0,
            "quality": 0,
            "security": 0,
            "description": "All workers adhere to the site PPE requirements.",
            "actionsTaken": null,
            "suggestion": "This is a good safety culture",
            "status": "Completed",
            "riskLevel": null,
            "bypassSafety": 0,
            "lineOfFire": 0,
            "workingAtHeight": 0,
            "hotWorK": 0,
            "driving": 0,
            "confinedSpace": 0,
            "permitToWork": 0,
            "energyIsolation": 0,
            "mechanicalLifting": 0,
            "correctiveAction": null,
            "editedBy": null,
            "dateAdded": "2024-11-21T12:32:19.000Z"
        },
        {
            "cardID": "CC-5594218",
            "cardTitle": "",
            "observerFirstname": "Justice ",
            "observerLastname": "Hercules",
            "observerEmail": "user1@example.com",
            "observerDepartment": "HSE",
            "observerDesignation": "Manager",
            "observerCountry": "Ghana",
            "observerLocation": "Head Office",
            "observationType": "Substandard Hazard",
            "peopleActs": 0,
            "condition": 1,
            "environmental": 0,
            "assetsEquipment": 0,
            "procedureSystem": 0,
            "quality": 0,
            "security": 0,
            "description": "A spill kit is absent in the workshop for the maintenance team.",
            "actionsTaken": "Yes",
            "suggestion": "A request will be made for a spill kit and stationed at the appropriate place.",
            "status": "Completed",
            "riskLevel": null,
            "bypassSafety": 0,
            "lineOfFire": 0,
            "workingAtHeight": 0,
            "hotWorK": 0,
            "driving": 0,
            "confinedSpace": 0,
            "permitToWork": 0,
            "energyIsolation": 0,
            "mechanicalLifting": 0,
            "correctiveAction": null,
            "editedBy": null,
            "dateAdded": "2024-11-21T12:29:04.000Z"
        },
        {
            "cardID": "CC-9397368",
            "cardTitle": "",
            "observerFirstname": "John",
            "observerLastname": "Koomson",
            "observerEmail": "user2@example.com",
            "observerDepartment": "HSE",
            "observerDesignation": "Graduate Trainee",
            "observerCountry": "Ghana",
            "observerLocation": "Head Office",
            "observationType": "Substandard Hazard",
            "peopleActs": 0,
            "condition": 1,
            "environmental": 0,
            "assetsEquipment": 0,
            "procedureSystem": 0,
            "quality": 0,
            "security": 0,
            "description": "Bins for the collection of oily contaminated waste should be provided for the maintenance team.",
            "actionsTaken": "Yes",
            "suggestion": "A request should be made to purchase new ones and stationed at vantage points.",
            "status": "Pending",
            "riskLevel": null,
            "bypassSafety": 0,
            "lineOfFire": 0,
            "workingAtHeight": 0,
            "hotWorK": 0,
            "driving": 0,
            "confinedSpace": 0,
            "permitToWork": 0,
            "energyIsolation": 0,
            "mechanicalLifting": 0,
            "correctiveAction": null,
            "editedBy": null,
            "dateAdded": "2024-11-21T12:25:43.000Z"
        },
        {
            "cardID": "CC-4310758",
            "cardTitle": "",
            "observerFirstname": "Arthur",
            "observerLastname": "Tawiah ",
            "observerEmail": "user3@example.com",
            "observerDepartment": "Maintenance",
            "observerDesignation": "Other",
            "observerCountry": "Ghana",
            "observerLocation": "Head Office",
            "observationType": "Substandard Hazard",
            "peopleActs": 0,
            "condition": 1,
            "environmental": 0,
            "assetsEquipment": 0,
            "procedureSystem": 0,
            "quality": 0,
            "security": 0,
            "description": "All the lights at the junior staff washrooms are burnt out making the place dark.",
            "actionsTaken": "Yes",
            "suggestion": "I reported to the HSE department",
            "status": "Completed",
            "riskLevel": null,
            "bypassSafety": 0,
            "lineOfFire": 0,
            "workingAtHeight": 0,
            "hotWorK": 0,
            "driving": 0,
            "confinedSpace": 0,
            "permitToWork": 0,
            "energyIsolation": 0,
            "mechanicalLifting": 0,
            "correctiveAction": null,
            "editedBy": null,
            "dateAdded": "2024-11-21T12:21:40.000Z"
        }
    ],
    "profilePictures": [
        {
            "profilepicture": "default.jpg",
            "email": "user1@example.com"
        },
        {
            "profilepicture": "default.jpg",
            "email": "user2@example.com"
        },
        {
            "profilepicture": "default.jpg",
            "email": "user3@example.com"
        },
        {
            "profilepicture": "default.jpg",
            "email": "user4@example.com"
        },
        {
            "profilepicture": "default.jpg",
            "email": "user5@example.com"
        }
    ]
}

export const admin = {
    "firstname": "Admin",
    "lastname": "Demo",
    "profilepicture": "default.jpg",
    "email": "admin@admin.com",
    "password": "$2a$13$gnx0oea0XQBQK55nd7WK/.R6CzL511gZtQCz2mvzR32QO2W0zRW/m",
    "location": "Ghana",
    "dateCreated": "2024-06-04T08:57:46.000Z",
    "code": "0000"
}